const rawOutcomes = [
  ['pending', 'Pendiente', 'Pendiente', '#94A3B8', 'waiting_response', 'Contactado', 1, 'Esperar respuesta y retomar según el canal.', 0, false, true, false, true],
  ['no_response_first_message', 'No respondió al primer mensaje', 'Sin respuesta', '#FACC15', 'waiting_response', 'Seguimiento 1', 1, 'Realizar follow-up en 24 horas.', 4, false, true, true, true],
  ['no_response_call', 'No respondió a la llamada', 'Sin respuesta', '#FACC15', 'waiting_response', 'Seguimiento 1', 1, 'Intentar WhatsApp o un segundo canal.', 4, false, true, true, true],
  ['outside_hours_auto_reply', 'Respuesta automática fuera de horario', 'Automatización', '#38BDF8', 'followup_scheduled', 'Seguimiento 1', 1, 'Contactar dentro del horario con el mensaje corregido.', 6, false, true, true, true],
  ['bot_requested_name_reason', 'Bot pidió nombre y motivo', 'Automatización', '#38BDF8', 'followup_scheduled', 'Seguimiento 1', 1, 'Enviar un follow-up corto solicitando al encargado.', 6, false, true, true, true],
  ['voicemail', 'Buzón de voz', 'Sin respuesta', '#FACC15', 'waiting_response', 'Seguimiento 1', 1, 'Intentar nuevamente o usar WhatsApp.', 3, false, true, true, true],
  ['reception', 'Recepción', 'Intermediario', '#A78BFA', 'waiting_decision_maker', 'Seguimiento 1', 1, 'Solicitar el nombre y horario del decisor.', 10, false, true, true, true],
  ['wrong_whatsapp_flow', 'WhatsApp abrió flujo de paciente', 'Canal incorrecto', '#FB923C', 'followup_scheduled', 'Seguimiento 1', 1, 'Aclarar el error y retomar como contacto comercial.', 7, false, true, true, true],
  ['contact_intermediary', 'Contacto con intermediario', 'Intermediario', '#A78BFA', 'waiting_decision_maker', 'Seguimiento 1', 1, 'Solicitar contacto o disponibilidad del decisor.', 14, false, false, true, true],
  ['referral', 'Referido a otro contacto', 'Referido', '#22D3EE', 'followup_scheduled', 'Seguimiento 1', 0, 'Crear o actualizar el contacto referido y escribirle.', 18, false, false, true, true],
  ['responded', 'Respondió', 'Respuesta', '#22D3EE', 'response_received', 'Respondió', 1, 'Calificar la necesidad y acordar el siguiente paso.', 25, false, false, true, true],
  ['requested_information', 'Solicitó información', 'Interés', '#86EFAC', 'conversation_active', 'Respondió', 1, 'Enviar información concreta y acordar seguimiento.', 24, false, false, true, true],
  ['followup_requested', 'Seguimiento solicitado', 'Seguimiento', '#C4B5FD', 'followup_scheduled', 'Seguimiento 1', 1, 'Retomar en la fecha acordada.', 18, false, false, true, true],
  ['waiting_confirmation', 'Esperando confirmación', 'Seguimiento', '#C4B5FD', 'waiting_confirmation', 'Seguimiento 1', 1, 'Confirmar la decisión o el horario acordado.', 28, false, false, true, true],
  ['objection_identified', 'Objeción identificada', 'Objeción', '#FB923C', 'conversation_active', 'Respondió', 2, 'Responder la objeción y validar el siguiente paso.', 16, false, false, true, true],
  ['decision_maker_unavailable', 'Decisor no disponible', 'Decisor', '#A78BFA', 'waiting_decision_maker', 'Seguimiento 1', 1, 'Contactar en el horario indicado.', 12, false, true, true, true],
  ['has_provider', 'Ya tiene proveedor', 'Objeción', '#94A3B8', 'followup_scheduled', 'Seguimiento 2', 60, 'Mantener en nurture y revisar en 60 días.', 4, false, false, true, true],
  ['interested', 'Interesado', 'Interés', '#B6FF2E', 'conversation_active', 'Interesado', 1, 'Acordar reunión o siguiente paso concreto.', 35, false, false, true, true],
  ['meeting_booked', 'Reunión agendada', 'Conversión', '#B6FF2E', 'closed', 'Reunión agendada', null, 'Preparar la reunión y confirmar asistencia.', 30, true, false, true, true],
  ['not_interested', 'No interesado', 'Cierre', '#F87171', 'closed', 'No interesado', null, 'Cerrar la oportunidad y conservar el historial.', -100, true, true, true, true],
  ['not_qualified', 'No califica', 'Cierre', '#F87171', 'closed', 'No califica', null, 'Cerrar la oportunidad con la razón documentada.', -100, true, false, true, true],
  ['invalid_number', 'Número incorrecto o inválido', 'Datos inválidos', '#EF4444', 'closed', 'No califica', null, 'Buscar otro canal; si no existe, descartar.', -100, true, true, true, true],
  ['do_not_contact', 'No contactar', 'Cierre', '#EF4444', 'closed', 'Descartado', null, 'No insistir. Conservar el historial.', -100, true, false, true, true],
  ['sale', 'Venta', 'Conversión', '#B6FF2E', 'closed', 'Implementación vendida', null, 'Iniciar onboarding y registrar el monto.', -100, true, false, true, true],
];

export const DEFAULT_OUTCOMES = rawOutcomes.map(([
  code,
  name,
  category,
  color,
  recommendedConversationStatus,
  recommendedCommercialStatus,
  followupDelayDays,
  recommendedNextStep,
  priorityAdjustment,
  isTerminal,
  availableForAction,
  availableForResponse,
  availableForClassification,
], index) => ({
  id: `local:${code}`,
  code,
  name,
  category,
  color,
  description: recommendedNextStep,
  recommended_conversation_status: recommendedConversationStatus,
  recommended_commercial_status: recommendedCommercialStatus,
  followup_delay_days: followupDelayDays,
  recommended_next_step: recommendedNextStep,
  priority_adjustment: priorityAdjustment,
  is_terminal: isTerminal,
  available_for_action: availableForAction,
  available_for_response: availableForResponse,
  available_for_classification: availableForClassification,
  is_active: true,
  sort_order: (index + 1) * 10,
  is_local_fallback: true,
}));

export function defaultOutcomesFor(context = 'classification') {
  const column = {
    action: 'available_for_action',
    response: 'available_for_response',
    classification: 'available_for_classification',
  }[context];
  if (!column || context === 'all') return DEFAULT_OUTCOMES;
  return DEFAULT_OUTCOMES.filter((item) => item[column]);
}
